/* The following code was generated by JFlex 1.6.0 */

/*Import*/
import java.io.*;
import java_cup.runtime.*;

/**
 * Conyo++ Language Lexer
 * CHUA, Jedrick
 * LIVELO, Evan Dennison
 * YAO, John Paul
 */

class ConyoLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHARACTER = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\2\6\1\3\1\105\1\105\1\5\22\0\1\6\1\0\1\104"+
    "\1\0\1\62\1\75\1\101\1\103\1\63\1\64\1\73\1\71\1\60"+
    "\1\72\1\11\1\74\1\10\11\2\1\61\1\0\1\76\1\100\1\77"+
    "\2\0\1\41\1\32\1\1\1\54\2\1\1\23\1\55\2\1\1\50"+
    "\1\16\1\22\1\44\1\21\1\51\1\1\1\52\1\47\1\34\1\46"+
    "\1\1\1\53\1\1\1\27\1\1\1\65\1\7\1\66\1\0\1\4"+
    "\1\0\1\14\1\30\1\57\1\31\1\12\1\56\1\17\1\24\1\25"+
    "\1\1\1\15\1\33\1\13\1\43\1\36\1\35\1\1\1\26\1\37"+
    "\1\42\1\40\1\1\1\45\1\1\1\20\1\1\1\67\1\102\1\70"+
    "\7\0\1\105\u1fa2\0\1\105\1\105\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\0\1\2\1\3\1\4\1\5\1\6"+
    "\1\5\1\4\1\7\20\3\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\2\1\30\1\31\1\32"+
    "\1\33\1\1\1\34\1\2\1\5\14\0\1\35\12\0"+
    "\1\36\1\37\1\40\1\41\1\42\2\43\2\0\1\44"+
    "\1\45\1\46\22\0\1\47\1\0\1\50\5\0\1\51"+
    "\3\0\1\52\3\0\1\53\2\43\13\0\1\54\2\0"+
    "\1\55\5\0\1\56\1\0\1\57\4\0\1\60\16\0"+
    "\1\61\15\0\1\62\4\0\1\63\2\0\1\64\1\0"+
    "\1\65\2\0\1\66\1\67\2\0\1\70\1\0\1\71"+
    "\1\72\4\0\1\73\1\74\1\75\1\76\1\0\1\77"+
    "\1\100\1\101\1\0\1\102\1\0\1\103\1\104\1\105"+
    "\4\0\1\106";

  private static int [] zzUnpackAction() {
    int [] result = new int[224];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\106\0\214\0\322\0\322\0\u0118\0\322\0\322"+
    "\0\u015e\0\u01a4\0\322\0\u01ea\0\u0230\0\u0276\0\u02bc\0\u0302"+
    "\0\u0348\0\u038e\0\u03d4\0\u041a\0\u0460\0\u04a6\0\u04ec\0\u0532"+
    "\0\u0578\0\u05be\0\u0604\0\322\0\322\0\322\0\322\0\322"+
    "\0\322\0\322\0\322\0\322\0\322\0\322\0\322\0\322"+
    "\0\322\0\u064a\0\u0690\0\u06d6\0\322\0\322\0\322\0\322"+
    "\0\u071c\0\322\0\u0762\0\u0762\0\u0762\0\u07a8\0\u07ee\0\u0834"+
    "\0\u087a\0\u08c0\0\u0906\0\u094c\0\u0992\0\u09d8\0\u0a1e\0\u0a64"+
    "\0\322\0\u0aaa\0\u0af0\0\u0b36\0\u0b7c\0\u0bc2\0\u0c08\0\u0c4e"+
    "\0\u0c94\0\u0cda\0\u0d20\0\322\0\322\0\322\0\322\0\322"+
    "\0\u0d66\0\u0dac\0\u0df2\0\u0e38\0\322\0\322\0\322\0\u0e7e"+
    "\0\u0ec4\0\u0f0a\0\u0f50\0\u0f96\0\u0fdc\0\u1022\0\u1068\0\u10ae"+
    "\0\u10f4\0\u113a\0\u1180\0\u11c6\0\u120c\0\u1252\0\u1298\0\u12de"+
    "\0\u1324\0\322\0\u136a\0\322\0\u13b0\0\u13f6\0\u143c\0\u1482"+
    "\0\u14c8\0\322\0\u150e\0\u1554\0\u159a\0\322\0\u15e0\0\u1626"+
    "\0\u166c\0\322\0\u16b2\0\322\0\u16f8\0\u173e\0\u1784\0\u17ca"+
    "\0\u1810\0\u1856\0\u189c\0\u18e2\0\u1928\0\u196e\0\u19b4\0\322"+
    "\0\u19fa\0\u1a40\0\322\0\u1a86\0\u1acc\0\u1b12\0\u1b58\0\u1b9e"+
    "\0\322\0\u1be4\0\322\0\u1c2a\0\u1c70\0\u1cb6\0\u1cfc\0\322"+
    "\0\u1d42\0\u1d88\0\u1dce\0\u1e14\0\u1e5a\0\u1ea0\0\u1ee6\0\u1f2c"+
    "\0\u1f72\0\u1fb8\0\u1ffe\0\u2044\0\u208a\0\u20d0\0\322\0\u2116"+
    "\0\u215c\0\u21a2\0\u21e8\0\u222e\0\u2274\0\u22ba\0\u2300\0\u2346"+
    "\0\u238c\0\u23d2\0\u2418\0\u245e\0\322\0\u24a4\0\u24ea\0\u2530"+
    "\0\u2576\0\322\0\u25bc\0\u2602\0\322\0\u2648\0\322\0\u268e"+
    "\0\u26d4\0\322\0\322\0\u271a\0\u2760\0\322\0\u27a6\0\322"+
    "\0\322\0\u27ec\0\u2832\0\u2878\0\u28be\0\322\0\322\0\322"+
    "\0\322\0\u2904\0\322\0\322\0\322\0\u294a\0\322\0\u2990"+
    "\0\322\0\322\0\u29d6\0\u2a1c\0\u2a62\0\u2aa8\0\u2aee\0\322";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[224];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\11\1\7\1\4"+
    "\1\12\1\13\1\5\1\14\4\5\1\15\1\16\1\17"+
    "\1\5\1\20\1\21\2\5\1\22\1\23\1\5\1\24"+
    "\1\5\1\25\1\5\1\26\2\5\1\27\1\30\1\5"+
    "\1\31\10\5\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\57"+
    "\1\60\1\0\3\61\1\7\1\61\1\11\1\61\1\4"+
    "\74\61\1\62\1\61\3\63\1\7\1\63\1\11\1\64"+
    "\1\4\74\63\1\4\1\65\110\0\1\6\5\0\1\6"+
    "\1\66\77\0\1\7\113\0\1\66\110\0\1\67\131\0"+
    "\1\70\67\0\1\71\135\0\1\72\1\0\1\73\56\0"+
    "\1\74\123\0\1\75\56\0\1\76\11\0\1\77\7\0"+
    "\1\100\77\0\1\101\102\0\1\102\116\0\1\103\107\0"+
    "\1\104\1\0\1\105\67\0\1\106\121\0\1\107\61\0"+
    "\1\110\124\0\1\111\76\0\1\112\16\0\1\113\141\0"+
    "\1\114\1\115\105\0\1\116\105\0\1\117\5\0\3\61"+
    "\1\0\1\61\1\0\1\61\1\0\74\61\1\0\1\61"+
    "\103\0\1\120\4\0\1\121\5\0\1\122\112\0\1\123"+
    "\114\0\1\124\104\0\1\125\135\0\1\126\104\0\1\127"+
    "\61\0\1\130\121\0\1\131\63\0\1\132\77\0\1\133"+
    "\1\0\1\134\127\0\1\135\64\0\1\136\126\0\1\137"+
    "\104\0\1\140\76\0\1\141\104\0\1\142\104\0\1\143"+
    "\114\0\1\144\110\0\1\145\63\0\1\146\111\0\1\147"+
    "\67\0\1\121\5\0\1\121\1\0\1\150\105\0\1\150"+
    "\105\0\1\151\117\0\1\152\73\0\1\153\113\0\1\154"+
    "\101\0\1\155\105\0\1\156\134\0\1\157\75\0\1\160"+
    "\64\0\1\161\121\0\1\162\71\0\1\163\120\0\1\164"+
    "\117\0\1\165\72\0\1\166\73\0\1\167\107\0\1\170"+
    "\117\0\1\171\115\0\1\172\51\0\1\173\5\0\1\174"+
    "\113\0\1\175\4\0\1\176\6\0\1\177\1\0\1\200"+
    "\3\0\1\201\1\202\4\0\1\203\1\204\1\205\1\206"+
    "\63\0\1\207\107\0\1\210\71\0\1\211\121\0\1\212"+
    "\74\0\1\213\135\0\1\214\4\0\1\215\56\0\1\216"+
    "\122\0\1\217\106\0\1\220\61\0\1\221\127\0\1\222"+
    "\63\0\1\223\67\0\1\173\5\0\1\173\111\0\1\224"+
    "\105\0\1\225\105\0\1\226\105\0\1\227\126\0\1\230"+
    "\76\0\1\231\112\0\1\232\6\0\1\233\103\0\1\234"+
    "\105\0\1\235\61\0\1\236\105\0\1\237\131\0\1\240"+
    "\111\0\1\241\55\0\1\242\105\0\1\243\120\0\1\244"+
    "\75\0\1\245\102\0\1\246\111\0\1\247\104\0\1\250"+
    "\133\0\1\251\73\0\1\252\3\0\1\253\103\0\1\254"+
    "\7\0\1\255\102\0\1\256\70\0\1\257\120\0\1\260"+
    "\100\0\1\261\76\0\1\262\114\0\1\263\72\0\1\264"+
    "\122\0\1\265\62\0\1\266\130\0\1\267\100\0\1\270"+
    "\71\0\1\271\111\0\1\272\120\0\1\273\66\0\1\274"+
    "\105\0\1\275\116\0\1\276\74\0\1\277\127\0\1\300"+
    "\63\0\1\301\103\0\1\302\135\0\1\303\102\0\1\304"+
    "\62\0\1\305\105\0\1\306\116\0\1\307\74\0\1\310"+
    "\136\0\1\311\54\0\1\312\105\0\1\313\111\0\1\314"+
    "\101\0\1\315\111\0\1\316\102\0\1\317\127\0\1\320"+
    "\65\0\1\321\102\0\1\322\133\0\1\323\105\0\1\324"+
    "\62\0\1\325\131\0\1\326\56\0\1\327\134\0\1\330"+
    "\105\0\1\331\61\0\1\332\105\0\1\333\136\0\1\334"+
    "\51\0\1\335\126\0\1\336\64\0\1\337\110\0\1\340"+
    "\66\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11060];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\1\0\2\11\1\1\2\11\2\1\1\11"+
    "\20\1\16\11\3\1\4\11\1\1\1\11\2\1\14\0"+
    "\1\11\12\0\5\11\2\1\2\0\3\11\22\0\1\11"+
    "\1\0\1\11\5\0\1\11\3\0\1\11\3\0\1\11"+
    "\1\1\1\11\13\0\1\11\2\0\1\11\5\0\1\11"+
    "\1\0\1\11\4\0\1\11\16\0\1\11\15\0\1\11"+
    "\4\0\1\11\2\0\1\11\1\0\1\11\2\0\2\11"+
    "\2\0\1\11\1\0\2\11\4\0\4\11\1\0\3\11"+
    "\1\0\1\11\1\0\2\11\1\1\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[224];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	StringBuffer string = new StringBuffer();

	private Symbol symbol(int type) {
		return new Symbol(type, yyline, yycolumn);
	}
	
	private Symbol symbol(int type, Object value) {
		return new Symbol(type, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  ConyoLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 224) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  private static String zzToPrintable(String str) {
    StringBuilder builder = new StringBuilder();
    for (int n = 0 ; n < str.length() ; ) {
      int ch = str.codePointAt(n);
      int charCount = Character.charCount(ch);
      n += charCount;
      if (ch > 31 && ch < 127) {
        builder.append((char)ch);
      } else if (charCount == 1) {
        builder.append(String.format("\\u%04X", ch));
      } else {
        builder.append(String.format("\\U%06X", ch));
      }
    }
    return builder.toString();
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [131] { return symbol(sym.STRING, yytext()); }");
          { return symbol(sym.STRING, yytext());
          }
        case 71: break;
        case 2: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [143] { System.out.println(\"Invalid.\"); }");
          { System.out.println("Invalid.");
          }
        case 72: break;
        case 3: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [123] { return symbol(sym.LETTER, yytext().charAt(0)); }");
          { return symbol(sym.LETTER, yytext().charAt(0));
          }
        case 73: break;
        case 4: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [122] { return symbol(sym.INTEGER, Integer.parseInt(yytext())); }");
          { return symbol(sym.INTEGER, Integer.parseInt(yytext()));
          }
        case 74: break;
        case 5: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [139] { /*blank*/ }");
          { /*blank*/
          }
        case 75: break;
        case 6: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [125] { return symbol(sym.UNDERSCORE, yytext().charAt(0)); }");
          { return symbol(sym.UNDERSCORE, yytext().charAt(0));
          }
        case 76: break;
        case 7: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [104] { return symbol(sym.PERIOD); }");
          { return symbol(sym.PERIOD);
          }
        case 77: break;
        case 8: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [95] { return symbol(sym.COMMA); }");
          { return symbol(sym.COMMA);
          }
        case 78: break;
        case 9: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [96] { return symbol(sym.COLON); }");
          { return symbol(sym.COLON);
          }
        case 79: break;
        case 10: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [97] { return symbol(sym.DOLLAR_SIGN); }");
          { return symbol(sym.DOLLAR_SIGN);
          }
        case 80: break;
        case 11: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [98] { return symbol(sym.LEFT_PAREN); }");
          { return symbol(sym.LEFT_PAREN);
          }
        case 81: break;
        case 12: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [99] { return symbol(sym.RIGHT_PAREN); }");
          { return symbol(sym.RIGHT_PAREN);
          }
        case 82: break;
        case 13: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [100] { return symbol(sym.LEFT_BRACE); }");
          { return symbol(sym.LEFT_BRACE);
          }
        case 83: break;
        case 14: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [101] { return symbol(sym.RIGHT_BRACE); }");
          { return symbol(sym.RIGHT_BRACE);
          }
        case 84: break;
        case 15: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [102] { return symbol(sym.LEFT_CURLY); }");
          { return symbol(sym.LEFT_CURLY);
          }
        case 85: break;
        case 16: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [103] { return symbol(sym.RIGHT_CURLY); }");
          { return symbol(sym.RIGHT_CURLY);
          }
        case 86: break;
        case 17: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [105] { return symbol(sym.PLUS); }");
          { return symbol(sym.PLUS);
          }
        case 87: break;
        case 18: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [106] { return symbol(sym.MINUS); }");
          { return symbol(sym.MINUS);
          }
        case 88: break;
        case 19: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [107] { return symbol(sym.TIMES); }");
          { return symbol(sym.TIMES);
          }
        case 89: break;
        case 20: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [108] { return symbol(sym.DIVIDE); }");
          { return symbol(sym.DIVIDE);
          }
        case 90: break;
        case 21: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [109] { return symbol(sym.MODULO); }");
          { return symbol(sym.MODULO);
          }
        case 91: break;
        case 22: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [111] { return symbol(sym.LESS_THAN); }");
          { return symbol(sym.LESS_THAN);
          }
        case 92: break;
        case 23: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [113] { return symbol(sym.GREATER_THAN); }");
          { return symbol(sym.GREATER_THAN);
          }
        case 93: break;
        case 24: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [116] { return symbol(sym.AND); }");
          { return symbol(sym.AND);
          }
        case 94: break;
        case 25: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [117] { return symbol(sym.OR); }");
          { return symbol(sym.OR);
          }
        case 95: break;
        case 26: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [118] { yybegin(CHARACTER); }");
          { yybegin(CHARACTER);
          }
        case 96: break;
        case 27: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [119] { yybegin(STRING); }");
          { yybegin(STRING);
          }
        case 97: break;
        case 28: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [130] { yybegin(YYINITIAL); return symbol(sym.MAKE_LAGAY); }");
          { yybegin(YYINITIAL); return symbol(sym.MAKE_LAGAY);
          }
        case 98: break;
        case 29: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [89] { return symbol(sym.DB); }");
          { return symbol(sym.DB);
          }
        case 99: break;
        case 30: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [110] { return symbol(sym.NOT_EQUAL); }");
          { return symbol(sym.NOT_EQUAL);
          }
        case 100: break;
        case 31: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [112] { return symbol(sym.LT_EQUAL); }");
          { return symbol(sym.LT_EQUAL);
          }
        case 101: break;
        case 32: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [114] { return symbol(sym.GT_EQUAL); }");
          { return symbol(sym.GT_EQUAL);
          }
        case 102: break;
        case 33: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [115] { return symbol(sym.EQUAL_EQUAL); }");
          { return symbol(sym.EQUAL_EQUAL);
          }
        case 103: break;
        case 34: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [136] { yybegin(YYINITIAL); return symbol(sym.CHARACTER, yytext().substring(0, 1)); }");
          { yybegin(YYINITIAL); return symbol(sym.CHARACTER, yytext().substring(0, 1));
          }
        case 104: break;
        case 35: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [124] { return symbol(sym.FLOAT, Float.parseFloat(yytext())); }");
          { return symbol(sym.FLOAT, Float.parseFloat(yytext()));
          }
        case 105: break;
        case 36: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [56] { return symbol(sym.OMG); }");
          { return symbol(sym.OMG);
          }
        case 106: break;
        case 37: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [74] { return symbol(sym.MRW); }");
          { return symbol(sym.MRW);
          }
        case 107: break;
        case 38: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [75] { return symbol(sym.MDR); }");
          { return symbol(sym.MDR);
          }
        case 108: break;
        case 39: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [84] { return symbol(sym.YUHH); }");
          { return symbol(sym.YUHH);
          }
        case 109: break;
        case 40: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [79] { return symbol(sym.INTY); }");
          { return symbol(sym.INTY);
          }
        case 110: break;
        case 41: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [86] { return symbol(sym.POOR); }");
          { return symbol(sym.POOR);
          }
        case 111: break;
        case 42: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [85] { return symbol(sym.NUHH); }");
          { return symbol(sym.NUHH);
          }
        case 112: break;
        case 43: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [90] { return symbol(sym.CNYO); }");
          { return symbol(sym.CNYO);
          }
        case 113: break;
        case 44: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [58] { return symbol(sym.BAYAD); }");
          { return symbol(sym.BAYAD);
          }
        case 114: break;
        case 45: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [83] { return symbol(sym.BOOLY); }");
          { return symbol(sym.BOOLY);
          }
        case 115: break;
        case 46: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [87] { return symbol(sym.WALEY); }");
          { return symbol(sym.WALEY);
          }
        case 116: break;
        case 47: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [81] { return symbol(sym.CHARY); }");
          { return symbol(sym.CHARY);
          }
        case 117: break;
        case 48: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [66] { return symbol(sym.MAKEUP); }");
          { return symbol(sym.MAKEUP);
          }
        case 118: break;
        case 49: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [80] { return symbol(sym.FLOATY); }");
          { return symbol(sym.FLOATY);
          }
        case 119: break;
        case 50: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [65] { return symbol(sym.BREAKUP); }");
          { return symbol(sym.BREAKUP);
          }
        case 120: break;
        case 51: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [82] { return symbol(sym.STRINGY); }");
          { return symbol(sym.STRINGY);
          }
        case 121: break;
        case 52: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [77] { return symbol(sym.MAKE_GAWA); }");
          { return symbol(sym.MAKE_GAWA);
          }
        case 122: break;
        case 53: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [69] { return symbol(sym.MAKE_BASA); }");
          { return symbol(sym.MAKE_BASA);
          }
        case 123: break;
        case 54: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [62] { return symbol(sym.MAKE_ARTE); }");
          { return symbol(sym.MAKE_ARTE);
          }
        case 124: break;
        case 55: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [78] { return symbol(sym.MAKE_ULIT); }");
          { return symbol(sym.MAKE_ULIT);
          }
        case 125: break;
        case 56: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [88] { return symbol(sym.MAKE_KUHA); }");
          { return symbol(sym.MAKE_KUHA);
          }
        case 126: break;
        case 57: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [57] { return symbol(sym.HIRE_YAYA); }");
          { return symbol(sym.HIRE_YAYA);
          }
        case 127: break;
        case 58: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [63] { return symbol(sym.BRAND_NEW); }");
          { return symbol(sym.BRAND_NEW);
          }
        case 128: break;
        case 59: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [55] { return symbol(sym.MAKE_LAGAY); }");
          { return symbol(sym.MAKE_LAGAY);
          }
        case 129: break;
        case 60: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [59] { return symbol(sym.MAKE_BALIK); }");
          { return symbol(sym.MAKE_BALIK);
          }
        case 130: break;
        case 61: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [60] { return symbol(sym.MAKE_TAPOS); }");
          { return symbol(sym.MAKE_TAPOS);
          }
        case 131: break;
        case 62: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [67] { return symbol(sym.MAKE_TAWAG); }");
          { return symbol(sym.MAKE_TAWAG);
          }
        case 132: break;
        case 63: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [68] { return symbol(sym.MAKE_SULAT); }");
          { return symbol(sym.MAKE_SULAT);
          }
        case 133: break;
        case 64: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [73] { return symbol(sym.MAKE_PALIT); }");
          { return symbol(sym.MAKE_PALIT);
          }
        case 134: break;
        case 65: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [70] { return symbol(sym.LIKE_KAPAG); }");
          { return symbol(sym.LIKE_KAPAG);
          }
        case 135: break;
        case 66: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [61] { return symbol(sym.SUPER_YAYA); }");
          { return symbol(sym.SUPER_YAYA);
          }
        case 136: break;
        case 67: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [64] { return symbol(sym.MAKE_UTUSAN); }");
          { return symbol(sym.MAKE_UTUSAN);
          }
        case 137: break;
        case 68: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [76] { return symbol(sym.LIKE_HABANG); }");
          { return symbol(sym.LIKE_HABANG);
          }
        case 138: break;
        case 69: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [71] { return symbol(sym.THIS_NALANG); }");
          { return symbol(sym.THIS_NALANG);
          }
        case 139: break;
        case 70: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
          System.out.println("action [72] { return symbol(sym.THIS_NALANG_KAPAG); }");
          { return symbol(sym.THIS_NALANG_KAPAG);
          }
        case 140: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: <<EOF>>");
                System.out.println("action [141] { return symbol(sym.EOF); }");
                return symbol(sym.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java ConyoLexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        ConyoLexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new ConyoLexer(reader);
          /*do {
            System.out.println(scanner.next_token());
          } while (!scanner.zzAtEOF);*/
	  Parser p = new Parser(scanner);
	  p.parse();

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
