
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int BREAKUP = 12;
  public static final int MAKE_SULAT = 15;
  public static final int MAKE_PALIT = 20;
  public static final int DIVIDE = 51;
  public static final int MDR = 22;
  public static final int RIGHT_PAREN = 42;
  public static final int POOR = 33;
  public static final int MAKE_ULIT = 25;
  public static final int DB = 37;
  public static final int PERIOD = 47;
  public static final int NOT_EQUAL = 53;
  public static final int INTEGER = 67;
  public static final int MAKEUP = 13;
  public static final int LEFT_CURLY = 45;
  public static final int MAKE_GAWA = 24;
  public static final int MINUS = 49;
  public static final int MAKE_LAGAY = 2;
  public static final int GREATER_THAN = 56;
  public static final int CHARACTER = 64;
  public static final int AND = 59;
  public static final int GT_EQUAL = 57;
  public static final int THIS_NALANG_KAPAG = 19;
  public static final int OR = 60;
  public static final int LEFT_BRACE = 43;
  public static final int COMMA = 38;
  public static final int BAYAD = 5;
  public static final int MAKE_TAWAG = 14;
  public static final int MRW = 21;
  public static final int THIS_NALANG = 18;
  public static final int RIGHT_CURLY = 46;
  public static final int PLUS = 48;
  public static final int MAKE_KUHA = 35;
  public static final int YUHH = 31;
  public static final int MAKE_BASA = 16;
  public static final int SUPER_YAYA = 8;
  public static final int HIRE_YAYA = 4;
  public static final int BOOLY = 30;
  public static final int EOF = 0;
  public static final int MAKE_TAPOS = 7;
  public static final int DOLLAR_SIGN = 40;
  public static final int error = 1;
  public static final int MODULO = 52;
  public static final int RIGHT_BRACE = 44;
  public static final int INTY = 26;
  public static final int CNYO = 61;
  public static final int WALEY = 34;
  public static final int LIKE_HABANG = 23;
  public static final int TIMES = 50;
  public static final int LT_EQUAL = 55;
  public static final int COLON = 39;
  public static final int LETTER = 65;
  public static final int MAKE_ARTE = 9;
  public static final int FLOAT = 66;
  public static final int MAKE_UTUSAN = 11;
  public static final int LEFT_PAREN = 41;
  public static final int MAKE_SIMULA = 36;
  public static final int UNDERSCORE = 68;
  public static final int STRING = 63;
  public static final int BRAND_NEW = 10;
  public static final int FLOATY = 27;
  public static final int LIKE_KAPAG = 17;
  public static final int NUHH = 32;
  public static final int LESS_THAN = 54;
  public static final int STRINGY = 29;
  public static final int MAKE_BALIK = 6;
  public static final int EQUAL_EQUAL = 58;
  public static final int OMG = 3;
  public static final int IDENTIFIER = 62;
  public static final int CHARY = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAKE_LAGAY",
  "OMG",
  "HIRE_YAYA",
  "BAYAD",
  "MAKE_BALIK",
  "MAKE_TAPOS",
  "SUPER_YAYA",
  "MAKE_ARTE",
  "BRAND_NEW",
  "MAKE_UTUSAN",
  "BREAKUP",
  "MAKEUP",
  "MAKE_TAWAG",
  "MAKE_SULAT",
  "MAKE_BASA",
  "LIKE_KAPAG",
  "THIS_NALANG",
  "THIS_NALANG_KAPAG",
  "MAKE_PALIT",
  "MRW",
  "MDR",
  "LIKE_HABANG",
  "MAKE_GAWA",
  "MAKE_ULIT",
  "INTY",
  "FLOATY",
  "CHARY",
  "STRINGY",
  "BOOLY",
  "YUHH",
  "NUHH",
  "POOR",
  "WALEY",
  "MAKE_KUHA",
  "MAKE_SIMULA",
  "DB",
  "COMMA",
  "COLON",
  "DOLLAR_SIGN",
  "LEFT_PAREN",
  "RIGHT_PAREN",
  "LEFT_BRACE",
  "RIGHT_BRACE",
  "LEFT_CURLY",
  "RIGHT_CURLY",
  "PERIOD",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MODULO",
  "NOT_EQUAL",
  "LESS_THAN",
  "LT_EQUAL",
  "GREATER_THAN",
  "GT_EQUAL",
  "EQUAL_EQUAL",
  "AND",
  "OR",
  "CNYO",
  "IDENTIFIER",
  "STRING",
  "CHARACTER",
  "LETTER",
  "FLOAT",
  "INTEGER",
  "UNDERSCORE"
  };
}

